### ISSUE TITLE
Handle parsing of the URI

### ISSUE THREAD

**Issue by urcadox** [CleverCloud/legacy-warp10-scala-client#1]
In my opinion, the client should not expect a `org.https4s.Uri` but a simple string.

It's the client's job to make sure that the URI is correct.

**Comment by waxzce** [comment]
I strongly disagree, Error handling of the Uri cannot be done by the client, so I will parse it to allow user to put a string, make an error management basically outputting error, and if users wants to do things right, he will par se it before, then send me a string ?????
I want my code drive developers to do things rigth, so I will not expose a string for a URI, but ask for URI

So, I want a URI, not a string, and I will get some valued object model.
